<?xml version="1.0"?>
<package format="3">
  <name>reliable_slam_toolbox_wrapper</name>
  <version>0.1.0</version>
  <description>Simulation validation wrapper for Slam Toolbox scan QoS.</description>
  <maintainer email="arash@example.invalid">Arash</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclcpp</depend>
  <depend>slam_toolbox</depend>
  <export><build_type>ament_cmake</build_type></export>
</package>
