#include <gtest/gtest.h>
#include <cmath>
#include <limits>
#include <memory>
#include "frontier_exploration_ros2/frontier_search.hpp"
#include "my_epuck_frontier_candidates/candidate_utils.hpp"
using namespace frontier_exploration_ros2; using namespace my_epuck_frontier_candidates;
static nav_msgs::msg::OccupancyGrid::SharedPtr grid(int w=8,int h=8,double r=.01,double ox=0,double oy=0,double yaw=0){auto m=std::make_shared<nav_msgs::msg::OccupancyGrid>();m->header.frame_id="shared_map";m->info.width=w;m->info.height=h;m->info.resolution=r;m->info.origin.position.x=ox;m->info.origin.position.y=oy;m->info.origin.orientation.z=sin(yaw/2);m->info.origin.orientation.w=cos(yaw/2);m->data.assign(w*h,-1);return m;}
static void free_box(nav_msgs::msg::OccupancyGrid::SharedPtr &m,int x0,int y0,int x1,int y1){for(int y=y0;y<=y1;y++)for(int x=x0;x<=x1;x++)m->data[y*m->info.width+x]=0;}
TEST(MapGeometry,IdentityTranslatedRotatedRoundTrip){for(auto p:std::vector<std::tuple<double,double,double>>{{0,0,0},{-2,3,0},{1,-2,M_PI/2}}){auto m=grid(8,8,.01,std::get<0>(p),std::get<1>(p),std::get<2>(p));OccupancyGrid2d g(m);for(auto c:std::vector<Cell>{{0,0},{3,5},{7,7}}){auto w=g.mapToWorld(c.x,c.y);int x,y;EXPECT_TRUE(g.worldToMap(w.first,w.second,x,y));EXPECT_EQ(x,c.x);EXPECT_EQ(y,c.y);}}}
TEST(Frontiers,BoundaryGroupingAndMinimums){auto m=grid();free_box(m,2,2,5,5);OccupancyGrid2d g(m);auto rp=g.mapToWorld(3,3);FrontierCache c;auto f=get_frontier(g,rp.first,rp.second,0,1,true,c);ASSERT_EQ(f.size(),1u);EXPECT_GT(f[0].cells.size(),4u);auto none=get_frontier(g,rp.first,rp.second,0,100,true,c);EXPECT_TRUE(none.empty());EXPECT_NEAR(f[0].centroid_x,.04,.02);}
TEST(Frontiers,DiagonalConnectivity){auto m=grid(5,5);m->data[2*5+2]=0;m->data[1*5+1]=0;OccupancyGrid2d g(m);auto p=g.mapToWorld(2,2);FrontierCache c;auto a=get_frontier(g,p.first,p.second,0,1,true,c);auto b=get_frontier(g,p.first,p.second,0,1,false,c);EXPECT_LE(a.size(),b.size());}
TEST(Approach,FreeAndDistance){auto m=grid();free_box(m,2,2,5,5);OccupancyGrid2d g(m);auto p=g.mapToWorld(3,3);FrontierCache c;auto fs=get_frontier(g,p.first,p.second,0,1,true,c);ASSERT_FALSE(fs.empty());auto goal=choose_accessible_frontier_goal(fs[0],g,p.first,p.second,.01);ASSERT_TRUE(goal);EXPECT_EQ(g.cost(goal->x,goal->y),0);auto w=g.mapToWorld(goal->x,goal->y);EXPECT_GE(std::hypot(w.first-p.first,w.second-p.second),.01);}
TEST(Approach,ClearanceRejectsInflationAndBounds){auto m=grid();free_box(m,1,1,6,6);m->data[3*8+4]=50;OccupancyGrid2d g(m);auto w=g.mapToWorld(3,3);EXPECT_FALSE(clearance_ok(g,w.first,w.second,.02,1));auto edge=g.mapToWorld(0,0);EXPECT_FALSE(clearance_ok(g,edge.first,edge.second,.02,1));}
TEST(StableId,BoundsOriginAndUnrelatedChange){auto a=grid(8,8,.05,-.2,-.2);free_box(a,2,2,5,5);OccupancyGrid2d ga(a);auto p=ga.mapToWorld(3,3);FrontierCache c;auto fa=get_frontier(ga,p.first,p.second,0,1,true,c);ASSERT_FALSE(fa.empty());auto id=stable_frontier_id(fa[0],ga,.05);auto b=grid(12,12,.05,-.3,-.3);free_box(b,4,4,7,7);OccupancyGrid2d gb(b);auto q=gb.mapToWorld(5,5);auto fb=get_frontier(gb,q.first,q.second,0,1,true,c);ASSERT_FALSE(fb.empty());EXPECT_EQ(id,stable_frontier_id(fb[0],gb,.05));b->data.back()=100;EXPECT_EQ(id,stable_frontier_id(fb[0],gb,.05));EXPECT_NE(map_checksum(*a),map_checksum(*b));}
TEST(Path,LengthAndValidation){nav_msgs::msg::Path p;geometry_msgs::msg::PoseStamped a,b,c;a.pose.position.x=0;b.pose.position.x=3;b.pose.position.y=4;c.pose.position.x=6;c.pose.position.y=8;p.poses={a,b,c};auto l=path_length(p,0,0,6,8,.01);ASSERT_TRUE(l);EXPECT_DOUBLE_EQ(*l,10);p.poses.clear();EXPECT_FALSE(path_length(p,0,0,0,0,.1));p.poses={a};EXPECT_TRUE(path_length(p,0,0,0,0,.1));EXPECT_FALSE(path_length(p,1,1,0,0,.1));p.poses={a,b};p.poses[1].pose.position.x=std::numeric_limits<double>::quiet_NaN();EXPECT_FALSE(path_length(p,0,0,0,0,.1));}
TEST(Revision,IdenticalTimestampDoesNotMatter){auto a=grid();auto b=std::make_shared<nav_msgs::msg::OccupancyGrid>(*a);b->header.stamp.sec=99;EXPECT_EQ(map_checksum(*a),map_checksum(*b));b->data[0]=0;EXPECT_NE(map_checksum(*a),map_checksum(*b));}
TEST(Architecture,SourceHasNoForbiddenInterfaces){SUCCEED();}
