#include <algorithm>
#include <atomic>
#include <chrono>
#include <cmath>
#include <deque>
#include <memory>
#include <random>
#include <string>
#include <unordered_map>
#include <vector>
#include <my_epuck_interfaces/msg/frontier_candidate_array.hpp>
#include <my_epuck_interfaces/msg/exploration_claim.hpp>
#include <nav2_msgs/action/navigate_to_pose.hpp>
#include <rclcpp/rclcpp.hpp>
#include <rclcpp_action/rclcpp_action.hpp>
#include "my_epuck_cooperative_exploration/coordinator.hpp"
#include "my_epuck_cooperative_exploration/protocol.hpp"
using namespace std::chrono_literals;
namespace my_epuck_cooperative_exploration {
class Coordinator:public rclcpp::Node{
 using CandidateArray=my_epuck_interfaces::msg::FrontierCandidateArray;using Candidate=my_epuck_interfaces::msg::FrontierCandidate;using Nav=nav2_msgs::action::NavigateToPose;using GoalHandle=rclcpp_action::ClientGoalHandle<Nav>;
 struct Metrics{uint64_t candidate_batches_received{},stale_candidate_batches{},candidates_rejected{},claims_created{},claims_published{},peer_claims_received{},peer_claims_accepted{},duplicate_peer_claims_rejected{},stale_peer_claims_rejected{},invalid_peer_claims_rejected{},retired_session_messages_rejected{},concurrent_session_messages_rejected{},peer_session_replacements{},peer_claim_expirations{},conflicts_detected{},arbitration_wins{},arbitration_losses{},proposal_releases{},final_releases{},navigation_goals_sent{},navigation_goals_accepted{},navigation_goals_rejected{},navigation_successes{},navigation_failures{},navigation_cancellations{},navigation_timeouts{},cancellation_requests{},cancellation_ack_timeouts{},stale_action_callbacks_ignored{},terminal_messages_published{},state_transitions{};};
public:explicit Coordinator(const rclcpp::NodeOptions & options):Node("cooperative_frontier_coordinator", options){
#define P(T,N,D) N##_=declare_parameter<T>(#N,D)
 P(std::string,robot_id,"");P(std::string,peer_robot_id,"");P(std::string,own_candidate_topic,"frontier_candidates");P(std::string,peer_claim_topic,"peer/exploration_claim");P(std::string,own_claim_topic,"exploration_claim");P(std::string,navigate_to_pose_action,"navigate_to_pose");P(std::string,global_frame,"map");P(double,arbitration_window_s,1.0);P(double,claim_heartbeat_rate_hz,2.0);P(double,claim_ttl_s,3.0);P(double,minimum_peer_ttl_s,.5);P(double,maximum_peer_ttl_s,10.0);P(double,terminal_broadcast_duration_s,1.0);P(double,terminal_broadcast_rate_hz,4.0);P(double,equivalent_frontier_centroid_tolerance_m,.15);P(double,equivalent_frontier_bbox_margin_m,.05);P(double,path_cost_tie_tolerance_m,.02);P(int,maximum_proposals_per_round,3);P(int,maximum_round_exclusion_records,16);P(int,maximum_retired_session_records,32);P(double,require_fresh_candidate_age_s,5.0);P(double,action_server_wait_timeout_s,10.0);P(double,navigation_goal_timeout_s,90.0);P(double,cancellation_ack_timeout_s,5.0);P(bool,autostart,true);P(bool,one_goal_only,true);P(int,test_candidate_rank,-1);P(std::string,test_frontier_id,"");
#undef P
 if(robot_id_.empty()||peer_robot_id_.empty()||robot_id_==peer_robot_id_)throw std::runtime_error("exactly one distinct robot_id and peer_robot_id are required");if(!one_goal_only_)throw std::runtime_error("this milestone requires one_goal_only=true");session_=new_uuid();cfg_={robot_id_,peer_robot_id_,global_frame_,minimum_peer_ttl_s_,maximum_peer_ttl_s_,equivalent_frontier_centroid_tolerance_m_,equivalent_frontier_bbox_margin_m_,path_cost_tie_tolerance_m_,size_t(maximum_retired_session_records_)};peer_=std::make_unique<PeerSessionTracker>(cfg_);
 auto cq=rclcpp::QoS(10).reliable().durability_volatile();candidate_sub_=create_subscription<CandidateArray>(own_candidate_topic_,rclcpp::QoS(1).reliable(),[this](CandidateArray::ConstSharedPtr x){candidate_cb(x);});peer_sub_=create_subscription<Claim>(peer_claim_topic_,cq,[this](Claim::ConstSharedPtr x){peer_cb(*x);});claim_pub_=create_publisher<Claim>(own_claim_topic_,cq);nav_=rclcpp_action::create_client<Nav>(this,navigate_to_pose_action_);started_=steady();last_heartbeat_=last_terminal_=last_diag_=started_;tick_=create_wall_timer(50ms,[this]{step();});RCLCPP_INFO(get_logger(),"coordinator node=%s namespace=%s robot=%s peer=%s candidate=%s peer_claim=%s own_claim=%s action=%s global_frame=%s candidate_qos=reliable,volatile,keep_last,depth=1 claim_qos=reliable,volatile,keep_last,depth=10 autostart=%s one_goal_only=%s session=%s",get_fully_qualified_name(),get_namespace(),robot_id_.c_str(),peer_robot_id_.c_str(),candidate_sub_->get_topic_name(),peer_sub_->get_topic_name(),claim_pub_->get_topic_name(),navigate_to_pose_action_.c_str(),global_frame_.c_str(),autostart_?"true":"false",one_goal_only_?"true":"false",uuid_key(session_).c_str());}
public:
 CoordinatorDiagnostics diagnostics() const{return {raw_candidate_callbacks_.load(),accepted_candidate_batches_.load(),nav_->action_server_is_ready()};}
private:
 static double finite_or(double x,double d){return std::isfinite(x)?x:d;}double steady()const{return std::chrono::duration<double>(std::chrono::steady_clock::now().time_since_epoch()).count();}
 static Uuid new_uuid(){Uuid u{};std::random_device rd;for(auto&b:u)b=uint8_t(rd());u[6]=(u[6]&0x0f)|0x40;u[8]=(u[8]&0x3f)|0x80;return u;}
 void transition(InternalState s){if(core_.state!=s){core_.state=s;m_.state_transitions++;}}
 bool candidate_valid(const Candidate&c)const{auto&p=c.approach_pose.pose.position;auto&q=c.approach_pose.pose.orientation;double n=q.x*q.x+q.y*q.y+q.z*q.z+q.w*q.w;return c.reachability_state==Candidate::REACHABLE&&std::isfinite(c.path_length_m)&&c.path_length_m>=0&&std::isfinite(c.information_gain)&&std::isfinite(c.score)&&std::isfinite(c.centroid.x)&&std::isfinite(c.centroid.y)&&std::isfinite(c.bounding_box_min.x)&&std::isfinite(c.bounding_box_min.y)&&std::isfinite(c.bounding_box_max.x)&&std::isfinite(c.bounding_box_max.y)&&c.bounding_box_min.x<=c.bounding_box_max.x&&c.bounding_box_min.y<=c.bounding_box_max.y&&std::isfinite(p.x)&&std::isfinite(p.y)&&std::isfinite(n)&&n>.5&&n<1.5&&c.approach_pose.header.frame_id==global_frame_;}
 void candidate_cb(CandidateArray::ConstSharedPtr b){auto raw=++raw_candidate_callbacks_;m_.candidate_batches_received++;if(raw==1)RCLCPP_INFO(get_logger(),"first raw candidate callback: source=%s frame=%s count=%zu",b->source_robot_id.c_str(),b->header.frame_id.c_str(),b->candidates.size());if(b->source_robot_id!=robot_id_){m_.candidates_rejected+=b->candidates.size();RCLCPP_WARN_THROTTLE(get_logger(),*get_clock(),5000,"candidate batch rejected: unexpected source %s",b->source_robot_id.c_str());return;}if(b->header.frame_id!=global_frame_){m_.candidates_rejected+=b->candidates.size();RCLCPP_WARN_THROTTLE(get_logger(),*get_clock(),5000,"candidate batch rejected: frame %s expected %s",b->header.frame_id.c_str(),global_frame_.c_str());return;}auto accepted=++accepted_candidate_batches_;if(accepted==1)RCLCPP_INFO(get_logger(),"first candidate batch accepted: revision=%lu candidates=%zu",b->map_revision,b->candidates.size());latest_=b;candidate_received_=steady();if((core_.state==InternalState::PROPOSING||core_.state==InternalState::ARBITRATING)&&current_&&!selected_present(*b)){release(false,"candidate_disappeared");}}
 bool selected_present(const CandidateArray&b)const{for(auto&c:b.candidates)if(c.frontier_id==current_->frontier_id||equivalent_frontiers(*current_,claim_from(c,current_->claim_id,Claim::PROPOSING,""),equivalent_frontier_centroid_tolerance_m_,equivalent_frontier_bbox_margin_m_))return true;return false;}
 void count_reject(ValidationCode c){if(c==ValidationCode::DUPLICATE_REVISION)m_.duplicate_peer_claims_rejected++;else if(c==ValidationCode::STALE_REVISION)m_.stale_peer_claims_rejected++;else if(c==ValidationCode::RETIRED_SESSION)m_.retired_session_messages_rejected++;else if(c==ValidationCode::CONCURRENT_SESSION)m_.concurrent_session_messages_rejected++;else m_.invalid_peer_claims_rejected++;}
 void peer_cb(const Claim&c){m_.peer_claims_received++;double now=steady();auto d=peer_->accept(c,now,!peer_->expired(now));if(d.code!=ValidationCode::OK){count_reject(d.code);return;}m_.peer_claims_accepted++;if(d.replacement)m_.peer_session_replacements++;peer_was_fresh_=true;auto pc=peer_->claim(now);if(!pc||!current_||!reserving(pc->state))return;auto result=arbitrate(*current_,*pc,equivalent_frontier_centroid_tolerance_m_,equivalent_frontier_bbox_margin_m_,path_cost_tie_tolerance_m_,true);if(result!=ArbitrationResult::NO_CONFLICT)m_.conflicts_detected++;if(core_.state==InternalState::NAVIGATING&&result==ArbitrationResult::PEER_WINS)request_cancel("delayed_peer_claim");}
 Claim claim_from(const Candidate&c,uint64_t id,uint8_t state,const std::string&reason)const{Claim x;x.header.frame_id=global_frame_;x.source_robot_id=robot_id_;std::copy(session_.begin(),session_.end(),x.source_session_id.uuid.begin());x.claim_id=id;x.state=state;x.frontier_id=c.frontier_id;x.map_revision=latest_?latest_->map_revision:0;x.frontier_centroid=c.centroid;x.bounding_box_min=c.bounding_box_min;x.bounding_box_max=c.bounding_box_max;x.approach_pose=c.approach_pose;x.path_length_m=c.path_length_m;x.information_gain=c.information_gain;x.utility_score=c.score;x.claim_ttl.sec=int32_t(claim_ttl_s_);x.claim_ttl.nanosec=uint32_t((claim_ttl_s_-std::floor(claim_ttl_s_))*1e9);x.state_reason=reason;return x;}
 void publish_claim(uint8_t state,const std::string&reason=""){if(!current_)return;current_->state=state;current_->state_reason=reason;current_->header.stamp=now();current_->message_revision=++message_revision_;claim_pub_->publish(*current_);m_.claims_published++;if(terminal(state))m_.terminal_messages_published++;RCLCPP_INFO(get_logger(),"CLAIM revision=%lu claim=%lu state=%u frontier=%lu centroid=(%.3f,%.3f) path=%.3f utility=%.3f map_revision=%lu ttl=%.3f reason=%s",current_->message_revision,current_->claim_id,current_->state,current_->frontier_id,current_->frontier_centroid.x,current_->frontier_centroid.y,current_->path_length_m,current_->utility_score,current_->map_revision,claim_ttl_s_,reason.c_str());}
 std::optional<Candidate> select(){if(!latest_||steady()-candidate_received_>require_fresh_candidate_age_s_)return{};int rank=0;for(auto&c:latest_->candidates){if(!candidate_valid(c)){m_.candidates_rejected++;continue;}if(std::find(excluded_.begin(),excluded_.end(),c.frontier_id)!=excluded_.end())continue;auto pc=peer_->claim(steady());auto tentative=claim_from(c,core_.claim_id+1,Claim::PROPOSING,"");if(pc&&reserving(pc->state)&&equivalent_frontiers(tentative,*pc,equivalent_frontier_centroid_tolerance_m_,equivalent_frontier_bbox_margin_m_))continue;if(!test_frontier_id_.empty()&&std::to_string(c.frontier_id)!=test_frontier_id_)continue;if(test_candidate_rank_>=0&&rank++!=test_candidate_rank_)continue;return c;}return{};}
 void create_proposal(){if(!core_.can_propose(maximum_proposals_per_round_)){final_release("proposal_budget_exhausted");return;}auto c=select();if(!c){if(current_)final_release("no_eligible_candidate");return;}core_.create_proposal();m_.claims_created++;current_=claim_from(*c,core_.claim_id,Claim::PROPOSING,"proposal");proposal_started_=steady();publish_claim(Claim::PROPOSING,"proposal");last_heartbeat_=steady();transition(InternalState::ARBITRATING);}
 void release(bool final,const std::string&reason){if(!current_)return;publish_claim(Claim::RELEASED,reason);if(final){m_.final_releases++;begin_terminal(Claim::RELEASED,reason);}else{m_.proposal_releases++;excluded_.push_back(current_->frontier_id);while(excluded_.size()>size_t(maximum_round_exclusion_records_))excluded_.erase(excluded_.begin());current_.reset();transition(InternalState::IDLE);}}
 void final_release(const std::string&reason){release(true,reason);}
 void dispatch(){if(!current_||core_.budget_consumed||core_.goals_sent)return;if(!nav_->action_server_is_ready()){final_release("action_server_unavailable");return;}Nav::Goal g;g.pose=current_->approach_pose;auto cid=current_->claim_id;core_.goals_sent++;m_.navigation_goals_sent++;auto opt=rclcpp_action::Client<Nav>::SendGoalOptions();opt.goal_response_callback=[this,cid](GoalHandle::SharedPtr h){if(!current_||cid!=current_->claim_id||core_.state!=InternalState::ARBITRATING){m_.stale_action_callbacks_ignored++;return;}if(!h){m_.navigation_goals_rejected++;begin_terminal(Claim::FAILED,"action_goal_rejected");return;}goal_=h;if(!core_.accept_goal()){m_.stale_action_callbacks_ignored++;return;}m_.navigation_goals_accepted++;accepted_at_=steady();publish_claim(Claim::NAVIGATING,"goal_accepted");};opt.feedback_callback=[this,cid](GoalHandle::SharedPtr,const std::shared_ptr<const Nav::Feedback>){if(!current_||cid!=current_->claim_id||core_.state!=InternalState::NAVIGATING)m_.stale_action_callbacks_ignored++;};opt.result_callback=[this,cid](const GoalHandle::WrappedResult&r){if(!current_||cid!=current_->claim_id||core_.state!=InternalState::NAVIGATING){m_.stale_action_callbacks_ignored++;return;}goal_.reset();if(cancel_pending_){m_.navigation_cancellations++;begin_terminal(Claim::CANCELED,cancel_reason_);return;}if(r.code==rclcpp_action::ResultCode::SUCCEEDED&&r.result&&r.result->error_code==0){m_.navigation_successes++;begin_terminal(Claim::SUCCEEDED,"navigation_succeeded");}else{m_.navigation_failures++;std::string reason="navigation_failed";if(r.result)reason+=":"+std::to_string(r.result->error_code)+":"+r.result->error_msg;begin_terminal(Claim::FAILED,reason);}};nav_->async_send_goal(g,opt);}
 void request_cancel(const std::string&reason){if(cancel_pending_||!goal_||core_.state!=InternalState::NAVIGATING)return;cancel_pending_=true;cancel_reason_=reason;cancel_requested_at_=steady();m_.cancellation_requests++;auto cid=current_->claim_id;nav_->async_cancel_goal(goal_,[this,cid](auto response){if(!current_||cid!=current_->claim_id||core_.state!=InternalState::NAVIGATING){m_.stale_action_callbacks_ignored++;return;}if(response&&!response->goals_canceling.empty()){m_.navigation_cancellations++;goal_.reset();begin_terminal(Claim::CANCELED,cancel_reason_+"_canceled");}else{goal_.reset();m_.navigation_failures++;begin_terminal(Claim::FAILED,cancel_reason_+"_cancel_rejected");}});}
 void begin_terminal(uint8_t state,const std::string&reason){terminal_state_=state;terminal_reason_=reason;terminal_started_=steady();last_terminal_=0;transition(InternalState::TERMINAL_BROADCAST);publish_claim(state,reason);}
 void finish_terminal(){transition(InternalState::IDLE_STOPPED);}
 void step(){double t=steady();if(peer_was_fresh_&&peer_->expired(t)){m_.peer_claim_expirations++;peer_was_fresh_=false;}if(core_.state==InternalState::WAITING_FOR_INPUTS){if(!autostart_)return;if(!latest_||t-candidate_received_>require_fresh_candidate_age_s_||!nav_->action_server_is_ready()){if(latest_&&t-candidate_received_>require_fresh_candidate_age_s_)m_.stale_candidate_batches++;return;}transition(InternalState::IDLE);}if(core_.state==InternalState::IDLE)create_proposal();else if(core_.state==InternalState::ARBITRATING){if(t-last_heartbeat_>=1./claim_heartbeat_rate_hz_){publish_claim(Claim::PROPOSING,"arbitrating");last_heartbeat_=t;}if(t-proposal_started_>=arbitration_window_s_){auto pc=peer_->claim(t);auto a=pc?arbitrate(*current_,*pc,equivalent_frontier_centroid_tolerance_m_,equivalent_frontier_bbox_margin_m_,path_cost_tie_tolerance_m_,true):ArbitrationResult::NO_CONFLICT;if(a==ArbitrationResult::PEER_WINS){m_.arbitration_losses++;release(false,"arbitration_lost");}else{m_.arbitration_wins++;dispatch();}}}else if(core_.state==InternalState::NAVIGATING){if(t-last_heartbeat_>=1./claim_heartbeat_rate_hz_){publish_claim(Claim::NAVIGATING,"navigating");last_heartbeat_=t;}if(!cancel_pending_&&t-accepted_at_>=navigation_goal_timeout_s_){m_.navigation_timeouts++;request_cancel("navigation_timeout");}if(cancel_pending_&&t-cancel_requested_at_>=cancellation_ack_timeout_s_){m_.cancellation_ack_timeouts++;goal_.reset();m_.navigation_failures++;begin_terminal(Claim::FAILED,cancel_reason_+"_ack_timeout");}}else if(core_.state==InternalState::TERMINAL_BROADCAST){if(t-last_terminal_>=1./terminal_broadcast_rate_hz_){publish_claim(terminal_state_,terminal_reason_);last_terminal_=t;}if(t-terminal_started_>=terminal_broadcast_duration_s_)finish_terminal();}if(t-last_diag_>=5){diag();last_diag_=t;}}
 void diag(){RCLCPP_INFO(get_logger(),"COORD_METRICS state=%d ext=%u claim=%lu session=%s peer_session=%s peer_age=%.3f proposals=%u pub=%lu peer_ok=%lu conflicts=%lu wins=%lu losses=%lu releases=%lu goals_sent=%lu goals_accepted=%lu success=%lu fail=%lu cancel=%lu budget=%d",int(core_.state),current_?current_->state:0,current_?current_->claim_id:0,uuid_key(session_).c_str(),peer_->active_key().c_str(),peer_->age(steady()),core_.proposals,m_.claims_published,m_.peer_claims_accepted,m_.conflicts_detected,m_.arbitration_wins,m_.arbitration_losses,m_.proposal_releases,m_.navigation_goals_sent,m_.navigation_goals_accepted,m_.navigation_successes,m_.navigation_failures,m_.navigation_cancellations,core_.budget_consumed);}
 std::atomic<uint64_t>raw_candidate_callbacks_{0},accepted_candidate_batches_{0};ProtocolConfig cfg_;std::unique_ptr<PeerSessionTracker>peer_;RoundCore core_;Metrics m_;Uuid session_{};CandidateArray::ConstSharedPtr latest_;double candidate_received_{0},started_{0},proposal_started_{0},accepted_at_{0},terminal_started_{0},cancel_requested_at_{0},last_heartbeat_{0},last_terminal_{0},last_diag_{0};uint64_t message_revision_{0};std::optional<Claim>current_;std::vector<uint64_t>excluded_;bool peer_was_fresh_{false},cancel_pending_{false};uint8_t terminal_state_{0};std::string terminal_reason_,cancel_reason_;GoalHandle::SharedPtr goal_;rclcpp_action::Client<Nav>::SharedPtr nav_;rclcpp::Subscription<CandidateArray>::SharedPtr candidate_sub_;rclcpp::Subscription<Claim>::SharedPtr peer_sub_;rclcpp::Publisher<Claim>::SharedPtr claim_pub_;rclcpp::TimerBase::SharedPtr tick_;
 std::string robot_id_,peer_robot_id_,own_candidate_topic_,peer_claim_topic_,own_claim_topic_,navigate_to_pose_action_,global_frame_,test_frontier_id_;double arbitration_window_s_,claim_heartbeat_rate_hz_,claim_ttl_s_,minimum_peer_ttl_s_,maximum_peer_ttl_s_,terminal_broadcast_duration_s_,terminal_broadcast_rate_hz_,equivalent_frontier_centroid_tolerance_m_,equivalent_frontier_bbox_margin_m_,path_cost_tie_tolerance_m_,require_fresh_candidate_age_s_,action_server_wait_timeout_s_,navigation_goal_timeout_s_,cancellation_ack_timeout_s_;int maximum_proposals_per_round_,maximum_round_exclusion_records_,maximum_retired_session_records_,test_candidate_rank_;bool autostart_,one_goal_only_;
};
rclcpp::Node::SharedPtr make_coordinator(const rclcpp::NodeOptions & options){return std::make_shared<Coordinator>(options);}
CoordinatorDiagnostics coordinator_diagnostics(const rclcpp::Node::SharedPtr & node){auto coordinator=std::dynamic_pointer_cast<Coordinator>(node);if(!coordinator)throw std::invalid_argument("node is not a production Coordinator");return coordinator->diagnostics();}
}

