#include "my_epuck_cooperative_exploration/protocol.hpp"
#include <algorithm>
#include <cmath>
#include <cstring>
#include <sstream>
namespace my_epuck_cooperative_exploration {
Uuid uuid_from_msg(const unique_identifier_msgs::msg::UUID&m){Uuid u{};std::copy(m.uuid.begin(),m.uuid.end(),u.begin());return u;}bool uuid_zero(const Uuid&u){return std::all_of(u.begin(),u.end(),[](auto b){return b==0;});}std::string uuid_key(const Uuid&u){std::ostringstream s;s<<std::hex;for(auto b:u){s.width(2);s.fill('0');s<<int(b);}return s.str();}
bool reserving(uint8_t s){return s==Claim::PROPOSING||s==Claim::NAVIGATING;}bool terminal(uint8_t s){return s==Claim::SUCCEEDED||s==Claim::FAILED||s==Claim::RELEASED||s==Claim::CANCELED;}
static bool fp(double x){return std::isfinite(x);}bool valid_quaternion(const geometry_msgs::msg::Quaternion&q){double n=q.x*q.x+q.y*q.y+q.z*q.z+q.w*q.w;return fp(n)&&n>.5&&n<1.5;}
bool finite_claim_geometry(const Claim&c){auto p=[](auto&v){return fp(v.x)&&fp(v.y)&&fp(v.z);};return p(c.frontier_centroid)&&p(c.bounding_box_min)&&p(c.bounding_box_max)&&p(c.approach_pose.pose.position)&&valid_quaternion(c.approach_pose.pose.orientation)&&c.bounding_box_min.x<=c.bounding_box_max.x&&c.bounding_box_min.y<=c.bounding_box_max.y&&(c.bounding_box_max.x-c.bounding_box_min.x>1e-9||c.bounding_box_max.y-c.bounding_box_min.y>1e-9);}
ValidationCode validate_claim_shape(const Claim&c,const ProtocolConfig&cfg){if(c.source_robot_id!=cfg.peer_robot_id)return c.source_robot_id==cfg.own_robot_id?ValidationCode::OWN_SOURCE:ValidationCode::UNEXPECTED_SOURCE;if(uuid_zero(uuid_from_msg(c.source_session_id)))return ValidationCode::ZERO_SESSION;if(c.state<Claim::PROPOSING||c.state>Claim::CANCELED)return ValidationCode::UNSUPPORTED_STATE;double ttl=c.claim_ttl.sec+c.claim_ttl.nanosec*1e-9;if(!fp(ttl)||ttl<cfg.min_ttl||ttl>cfg.max_ttl)return ValidationCode::INVALID_TTL;if(!fp(c.path_length_m)||!fp(c.information_gain)||!fp(c.utility_score))return ValidationCode::NONFINITE;if(c.approach_pose.header.frame_id!=cfg.global_frame)return ValidationCode::WRONG_FRAME;if(!valid_quaternion(c.approach_pose.pose.orientation))return ValidationCode::INVALID_QUATERNION;if(!finite_claim_geometry(c))return ValidationCode::INVALID_BOUNDS;return ValidationCode::OK;}
bool equivalent_frontiers(const Claim&a,const Claim&b,double ct,double margin){if(!finite_claim_geometry(a)||!finite_claim_geometry(b))return false;if(a.frontier_id==b.frontier_id)return true;if(std::hypot(a.frontier_centroid.x-b.frontier_centroid.x,a.frontier_centroid.y-b.frontier_centroid.y)>ct)return false;return a.bounding_box_min.x-margin<=b.bounding_box_max.x+margin&&b.bounding_box_min.x-margin<=a.bounding_box_max.x+margin&&a.bounding_box_min.y-margin<=b.bounding_box_max.y+margin&&b.bounding_box_min.y-margin<=a.bounding_box_max.y+margin;}
ArbitrationResult arbitrate(const Claim&l,const Claim&p,double ct,double bm,double tie,bool fresh){if(!fresh||!reserving(p.state)||!reserving(l.state)||!equivalent_frontiers(l,p,ct,bm))return ArbitrationResult::NO_CONFLICT;bool lf=fp(l.path_length_m),pf=fp(p.path_length_m);if(lf!=pf)return lf?ArbitrationResult::LOCAL_WINS:ArbitrationResult::PEER_WINS;if(!lf)return l.source_robot_id<=p.source_robot_id?ArbitrationResult::LOCAL_WINS:ArbitrationResult::PEER_WINS;if(std::abs(l.path_length_m-p.path_length_m)<=tie)return l.source_robot_id<p.source_robot_id?ArbitrationResult::LOCAL_WINS:ArbitrationResult::PEER_WINS;return l.path_length_m<p.path_length_m?ArbitrationResult::LOCAL_WINS:ArbitrationResult::PEER_WINS;}
void PeerSessionTracker::retire_active(){if(active_key_.empty())return;retired_.push_back(active_key_);while(retired_.size()>config_.max_retired_sessions)retired_.pop_front();active_key_.clear();claim_.reset();highest_revision_=0;}
SessionDecision PeerSessionTracker::accept(const Claim&c,double now,bool fresh){auto shape=validate_claim_shape(c,config_);if(shape!=ValidationCode::OK)return{shape,false};auto key=uuid_key(uuid_from_msg(c.source_session_id));if(std::find(retired_.begin(),retired_.end(),key)!=retired_.end())return{ValidationCode::RETIRED_SESSION,false};bool replacement=false;if(active_key_.empty()){active_key_=key;}else if(key!=active_key_){if(fresh)return{ValidationCode::CONCURRENT_SESSION,false};retire_active();active_key_=key;replacement=true;}if(c.message_revision==highest_revision_)return{ValidationCode::DUPLICATE_REVISION,false};if(c.message_revision<highest_revision_)return{ValidationCode::STALE_REVISION,false};highest_revision_=c.message_revision;received_at_=now;ttl_=c.claim_ttl.sec+c.claim_ttl.nanosec*1e-9;claim_=c;return{ValidationCode::OK,replacement};}
bool PeerSessionTracker::expired(double now)const{return !claim_||now-received_at_>ttl_;}std::optional<Claim> PeerSessionTracker::claim(double now)const{return expired(now)?std::nullopt:claim_;}double PeerSessionTracker::age(double now)const{return claim_?std::max(0.,now-received_at_):INFINITY;}
void RoundCore::create_proposal(){++claim_id;++proposals;state=InternalState::PROPOSING;}bool RoundCore::dispatch_once(){if(budget_consumed||goals_sent)return false;++goals_sent;state=InternalState::ARBITRATING;return true;}bool RoundCore::accept_goal(){if(budget_consumed||goals_accepted>=1)return false;++goals_accepted;budget_consumed=true;state=InternalState::NAVIGATING;return true;}void RoundCore::terminal_stop(){state=InternalState::IDLE_STOPPED;}
}
